# Mulai dari image Nginx Alpine yang ringan
FROM nginx:alpine

# Hapus konfigurasi default
RUN rm /etc/nginx/conf.d/default.conf

# Salin file konfigurasi utama
COPY nginx.conf /etc/nginx/nginx.conf

# Salin folder sertifikat SSL
COPY ssl/ /etc/nginx/ssl/
